### ISSUE TITLE
Can you please include steps to run this project it would help me  a lot..

### ISSUE THREAD

**Issue by Surajpnaik36** [Shahaed/Intelligent-Transplants#3]

**Comment by Shahaed** [comment]
There's no "one way" to just run the project. It's a collection of different tools we used to demonstrate the concept.

The project has these following components:

- A webscrapper to get the data in the 'selenium_webscrapper' folder 
  - This did not work well since days is not easily available and was not used to train our model
- Scripts to generate synthetic data in the 'syn...' folder.
  - We did use this to train our model
- The trained model and the code we used to train the model in the 'deep_learning' folder
- A REST Api in the 'api' folder to serve the model
- The rest of the code is a web application with basic auth using firebase and consuming the api

This is not a refined product and just a proof of concept. Since much of the code is outdated and may need significant effort to run, I would suggest this project to be used more as a potential guide in how something like this may be done.
